# Generated by Django 3.0.6 on 2020-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Stacy', max_length=255),
        ),
    ]
